# Generated by Django 5.0.14 on 2026-07-03 05:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='dependencies',
            field=models.ManyToManyField(blank=True, related_name='dependents', to='projects.task'),
        ),
        migrations.AddField(
            model_name='task',
            name='x_position',
            field=models.FloatField(default=100.0),
        ),
        migrations.AddField(
            model_name='task',
            name='y_position',
            field=models.FloatField(default=100.0),
        ),
    ]
