# Generated by Django 5.0.14 on 2026-07-03 06:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0002_task_dependencies_task_x_position_task_y_position'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='x_position',
            field=models.FloatField(default=100.0),
        ),
        migrations.AddField(
            model_name='project',
            name='y_position',
            field=models.FloatField(default=40.0),
        ),
        migrations.AlterField(
            model_name='task',
            name='y_position',
            field=models.FloatField(default=520.0),
        ),
        migrations.CreateModel(
            name='Sprint',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('x_position', models.FloatField(default=100.0)),
                ('y_position', models.FloatField(default=280.0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sprints', to='projects.project')),
            ],
        ),
        migrations.AddField(
            model_name='task',
            name='sprint',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tasks', to='projects.sprint'),
        ),
    ]
