# Generated by Django 5.0.14 on 2026-07-03 06:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0003_project_x_position_project_y_position_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='expected_finish_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='task',
            name='notes',
            field=models.TextField(blank=True),
        ),
    ]
