# Generated by Django 5.0.14 on 2026-07-03 06:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0004_task_expected_finish_date_task_notes'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='status',
            field=models.CharField(choices=[('TODO', 'À faire'), ('IN_PROGRESS', 'En cours'), ('TESTED', 'Testé'), ('DEPLOYED', 'Déployé'), ('DONE', 'Terminé')], default='TODO', max_length=20),
        ),
    ]
