steps:
  # Build Docker image
  - name: 'gcr.io/cloud-builders/docker'
    args:
      - 'build'
      - '-t'
      - '${_REGION}-docker.pkg.dev/${PROJECT_ID}/${_REPO}/admin:${SHORT_SHA}'
      - '-t'
      - '${_REGION}-docker.pkg.dev/${PROJECT_ID}/${_REPO}/admin:latest'
      - '.'

  # Push vers Artifact Registry
  - name: 'gcr.io/cloud-builders/docker'
    args:
      - 'push'
      - '--all-tags'
      - '${_REGION}-docker.pkg.dev/${PROJECT_ID}/${_REPO}/admin'

  # Déployer sur Cloud Run
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    entrypoint: gcloud
    args:
      - 'run'
      - 'deploy'
      - 'paramynd-admin'
      - '--image=${_REGION}-docker.pkg.dev/${PROJECT_ID}/${_REPO}/admin:${SHORT_SHA}'
      - '--region=${_REGION}'
      - '--platform=managed'
      - '--allow-unauthenticated'
      - '--set-env-vars=DJANGO_SETTINGS_MODULE=core.settings,EMAIL_BACKEND=django.core.mail.backends.smtp.EmailBackend,TWILIO_FROM_NUMBER=+33939249408,DEFAULT_FROM_EMAIL=service@lageniale.com'
      - '--set-secrets=SECRET_KEY=PARAMYND_ADMIN_SECRET_KEY:latest,DB_PASSWORD=PARAMYND_ADMIN_DB_PASSWORD:latest,DB_NAME=PARAMYND_ADMIN_DB_NAME:latest,DB_USER=PARAMYND_ADMIN_DB_USER:latest,ALLOWED_ADMIN_EMAILS=PARAMYND_ADMIN_ALLOWED_EMAILS:latest,CORS_ALLOWED_ORIGINS=PARAMYND_ADMIN_CORS_ORIGINS:latest,ALLOWED_HOSTS=PARAMYND_ADMIN_ALLOWED_HOSTS:latest,DEBUG=PARAMYND_ADMIN_DEBUG:latest,EMAIL_HOST_USER=POSTMARK_SERVER_TOKEN:latest,EMAIL_HOST_PASSWORD=POSTMARK_SERVER_TOKEN:latest,TWILIO_ACCOUNT_SID=TWILIO_ACCOUNT_SID:latest,TWILIO_AUTH_TOKEN=TWILIO_AUTH_TOKEN:latest,GITHUB_TOKEN=GITHUB_TOKEN:latest'
      - '--set-cloudsql-instances=${_CLOUD_SQL_INSTANCE}'
      - '--min-instances=1'
      - '--max-instances=5'

substitutions:
  _REGION: europe-west9
  _REPO: paramynd
  _CLOUD_SQL_INSTANCE: yellow-455523:europe-west9:yellow-db-paris

tags:
  - 'paramynd-admin'
  - '${SHORT_SHA}'

options:
  logging: CLOUD_LOGGING_ONLY
