# Generated by Django 5.0.14 on 2026-06-23 01:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tenants', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CloudBuildRecord',
            fields=[
                ('build_id', models.CharField(max_length=100, primary_key=True, serialize=False, verbose_name='ID du build')),
                ('status', models.CharField(max_length=50, verbose_name='Statut')),
                ('created_str', models.CharField(max_length=100, verbose_name='Créé le')),
                ('duration', models.CharField(max_length=50, verbose_name='Durée')),
                ('commit_sha', models.CharField(blank=True, max_length=40, null=True, verbose_name='Commit SHA')),
                ('branch_name', models.CharField(blank=True, max_length=255, null=True, verbose_name='Nom de branche')),
                ('tags', models.JSONField(default=list, verbose_name='Tags')),
                ('fetched_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Cloud Build',
                'db_table': 'tenants_cloud_build',
                'ordering': ['-fetched_at'],
            },
        ),
        migrations.CreateModel(
            name='GitCommitRecord',
            fields=[
                ('hash', models.CharField(max_length=40, primary_key=True, serialize=False, verbose_name='Hash complet')),
                ('short_hash', models.CharField(max_length=10, verbose_name='Hash court')),
                ('message', models.TextField(verbose_name='Message du commit')),
                ('author', models.CharField(max_length=255, verbose_name='Auteur')),
                ('date_str', models.CharField(max_length=100, verbose_name='Date string')),
                ('branch', models.CharField(blank=True, max_length=255, null=True, verbose_name='Branche')),
                ('fetched_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Commit Git',
                'db_table': 'tenants_git_commit',
                'ordering': ['-fetched_at'],
            },
        ),
    ]
