# Generated by Django 5.0.14 on 2026-06-23 03:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tenants', '0002_cloudbuildrecord_gitcommitrecord'),
    ]

    operations = [
        migrations.AddField(
            model_name='cloudbuildrecord',
            name='images',
            field=models.JSONField(default=list, verbose_name='Images Docker'),
        ),
    ]
