# Generated by Django 5.0.14 on 2026-06-23 04:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tenants', '0003_cloudbuildrecord_images'),
    ]

    operations = [
        migrations.CreateModel(
            name='SaaSGitCommitRecord',
            fields=[
                ('hash', models.CharField(max_length=40, primary_key=True, serialize=False, verbose_name='Hash complet')),
                ('short_hash', models.CharField(max_length=10, verbose_name='Hash court')),
                ('message', models.TextField(verbose_name='Message du commit')),
                ('author', models.CharField(max_length=255, verbose_name='Auteur')),
                ('date_str', models.CharField(max_length=100, verbose_name='Date string')),
                ('branch', models.CharField(blank=True, max_length=255, null=True, verbose_name='Branche')),
                ('fetched_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Commit Git SaaS',
                'db_table': 'tenants_saas_git_commit',
                'ordering': ['-fetched_at'],
            },
        ),
    ]
