# Generated by Django 5.0.14 on 2026-06-23 04:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tenants', '0004_saasgitcommitrecord'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='gitcommitrecord',
            options={'ordering': ['-commit_date_iso'], 'verbose_name': 'Commit Git'},
        ),
        migrations.AlterModelOptions(
            name='saasgitcommitrecord',
            options={'ordering': ['-commit_date_iso'], 'verbose_name': 'Commit Git SaaS'},
        ),
        migrations.AddField(
            model_name='gitcommitrecord',
            name='commit_date_iso',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Date ISO du commit'),
        ),
        migrations.AddField(
            model_name='gitcommitrecord',
            name='tag',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Tag'),
        ),
        migrations.AddField(
            model_name='saasgitcommitrecord',
            name='commit_date_iso',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Date ISO du commit'),
        ),
        migrations.AddField(
            model_name='saasgitcommitrecord',
            name='tag',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Tag'),
        ),
    ]
