# Generated by Django 5.0.14 on 2026-06-23 17:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tenants', '0005_alter_gitcommitrecord_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='tenant',
            name='dns_records',
            field=models.JSONField(blank=True, null=True, verbose_name='Enregistrements DNS requis'),
        ),
        migrations.AddField(
            model_name='tenant',
            name='domain_status',
            field=models.CharField(choices=[('none', 'Non configuré'), ('pending', 'En attente de propagation DNS'), ('active', 'Actif et sécurisé'), ('failed', 'Échec de configuration')], default='none', max_length=20, verbose_name='Statut du domaine'),
        ),
    ]
