# Generated by Django 5.0.14 on 2026-06-24 23:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tenants', '0006_tenant_dns_records_tenant_domain_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='cloudbuildrecord',
            name='progress',
            field=models.IntegerField(default=0, verbose_name='Progression (%)'),
        ),
    ]
