# Generated by Django 5.0.14 on 2026-06-26 03:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tenants', '0007_cloudbuildrecord_progress'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='gitcommitrecord',
            options={'ordering': ['-fetched_at'], 'verbose_name': 'Commit Git'},
        ),
        migrations.AlterModelOptions(
            name='saasgitcommitrecord',
            options={'ordering': ['-fetched_at'], 'verbose_name': 'Commit Git SaaS'},
        ),
        migrations.AlterField(
            model_name='tenant',
            name='status',
            field=models.CharField(choices=[('provisioning', 'En cours de provisionnement'), ('active', 'Actif'), ('paused', 'Mis en pause'), ('failed', 'En erreur'), ('archived', 'Archivé'), ('deleting', 'Suppression en cours')], default='provisioning', max_length=20, verbose_name='Statut'),
        ),
    ]
