# Generated by Django 5.0.14 on 2026-06-26 05:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tenants', '0008_add_deleting_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='tenant',
            name='provisioning_step',
            field=models.CharField(blank=True, default='', help_text='Ex: db_create, cr_deploy, migrate, superuser, done', max_length=50, verbose_name='Étape provisioning en cours'),
        ),
    ]
