# Generated by Django 5.0.14 on 2026-06-23 00:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_alter_user_managers_user_phone_number_and_more'),
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='GroupAccess',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('can_access_tenants', models.BooleanField(default=False, verbose_name='Clients (Tenants)')),
                ('can_access_builds', models.BooleanField(default=False, verbose_name='Builds & Images')),
                ('can_access_monitoring', models.BooleanField(default=False, verbose_name='Monitoring')),
                ('can_access_users', models.BooleanField(default=False, verbose_name='Gestion des Utilisateurs')),
                ('can_access_roles', models.BooleanField(default=False, verbose_name='Matrice des Rôles')),
                ('group', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='access', to='auth.group')),
            ],
        ),
    ]
