# Generated by Django 5.0.14 on 2026-06-26 03:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_user_email_verification_code_user_email_verified_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='otp_email_expires_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Expiration OTP email'),
        ),
        migrations.AddField(
            model_name='user',
            name='otp_phone_expires_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Expiration OTP SMS'),
        ),
    ]
