# Generated by Django 5.0.14 on 2026-06-27 00:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_add_otp_expiration_fields'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='otp_attempts',
            field=models.PositiveSmallIntegerField(default=0, verbose_name='Tentatives OTP'),
        ),
    ]
